#    volumes:
#      - type: volume
#        source: mydata
#        target: /data
#        # nocopy has no equivalent in the short syntax:
#        volume:
#          nocopy: true
#      - type: bind

services:
  interpreter:

    image: ${ORG}.${PACKAGE}:dev

    container_name: ${ORG}.${PACKAGE}
    env_file:
      - /opt/dev/repo/env
    volumes:
      - type: volume
        source: dev
        target: /opt/dev/repo
    #         volume:
    #           nocopy: true



    network_mode: host
    user: "1000:1000"

    environment:
      FMTR_DEV_SSH_PORT: ${PORT}

    pull_policy: build
    build:
      context: .

      #pull: true

      dockerfile: Dockerfile
      target: ${CHANNEL:-dev}
      secrets:
        - source: hf_token

      args:
        ORG: ${ORG}
        PACKAGE: ${PACKAGE}
        BASE: ${BASE}
        EXTRAS: ${EXTRAS}

      tags:
        - ${ORG}.${PACKAGE}:${CHANNEL:-dev}
        - ${ORG}.${PACKAGE}:${CHANNEL:-dev}-${VERSION}
      platforms:
        - linux/amd64
      additional_contexts:
        package: .
    x-bake:
      load: true  # Required if you want the image loaded locally

secrets:
  hf_token:
    environment: HF_TOKEN


volumes:
  dev:
    name: ${ORG}.${PACKAGE}