FROM fmtr/pytorch

WORKDIR /fmtr/tools
COPY --from=tools ../requirements.py .
RUN python requirements.py pdf,logging,debug,ai.client > requirements.txt
RUN pip install -r requirements.txt --no-cache-dir