#!/bin/bash

. parse-args "$@"

NAME=$(basename "$FILE")

cp "$FILE" ~/.config/systemd/user/
systemctl --user daemon-reload
systemctl --user enable "$NAME"
systemctl --user start "$NAME"
journalctl --user -u "$NAME" -f
