#!/bin/bash

. parse-args "$@"

set -eux

unset DOCKER_HOST
CONTEXT=${CONTEXT:-cloud}
export DOCKER_CONTEXT=$CONTEXT
echo "Using context $DOCKER_CONTEXT"

docker buildx create --name multi --driver docker-container --use ${CONTEXT}
echo $CONTAINER_INDEX_PUBLIC_TOKEN | docker login --username fmtr --password-stdin

build() {
  local NAME="$1"

  docker buildx build --progress=plain --builder multi /opt/dev/repo/scripts/base/${NAME} \
    --build-arg VERSION=${VERSION} \
    --tag fmtr/${NAME}:v${VERSION} --tag fmtr/${NAME}:latest \
    --platform linux/amd64,linux/arm64 \
    --push
}

build python
build pytorch
