#!/bin/bash

sudo qemu-system-x86_64 \
  -enable-kvm \
  -m 12G \
  -smp 4 \
  -cpu host \
  -machine q35 \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
  -drive if=pflash,format=raw,file=/usr/share/OVMF/OVMF_VARS_4M.fd \
  -drive file=/opt/dev/vm/ha/ha.qcow2,format=qcow2,if=virtio,cache=writeback,aio=threads \
  -device virtio-net-pci,netdev=net0 \
  -netdev bridge,id=net0,br=br0 \
  -display none \
  -serial mon:stdio