#!/bin/bash

set -ex

USERNAME=${USERNAME-$(whoami)}

sudo mkdir -p /opt/dev/ve
sudo chown ${USERNAME}:${USERNAME} -R /opt/dev

sudo apt install python3-venv --yes
python -m venv /opt/dev/ve/shell
sudo ln -s /opt/dev/ve/shell/bin/run-script /rss
source /opt/dev/ve/shell/bin/activate

sudo set-user-sudo --username=$USERNAME
sudo set-secure-path

echo "source /opt/dev/ve/shell/bin/activate" >> ~/.bashrc

